create table ramana(last_name varchar2(30),regd_no varchar(3),salary number(6));
insert into table1 values('venkata',45000);
alter table ramana modify regd_no varchar2(10);
insert into table1 values('&name','&g','&sal');
select * from table1;
rename ramana to table1;
update table1 set regd_no= 4466 where last_name='k';
--alter table table1 set regd_no='20K61A0497' where regd_no='20k497';
insert into table1(last_name,salary) values('&name','&sal');
delete from table1 where last_name='k';
update table1 set last_name='jhansi' where salary=67;
rollback;
truncate table table1;
rollback;

create table jhansi2(name1 varchar2(20),regd_no varchar2(15),mb_number number(11));
insert into jhansi2 values('&name','&num',&number);
savepoint a;
insert into jhansi2 values('jhansi','485',1234567899);
savepoint b;
insert into jhansi2 values('jhanc','480',1234567879);
savepoint c;
rollback to b;
select * from jhansi2;
drop table jhansi2;
create table sqls(id_num number(4) primary key,last_name varchar2(20) not null,mobile_num number(10) unique);
insert into sqls values(123,'abc',123456789);
insert into sqls values(12,'abc',123456780);
select * from sqls;  
